// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiirlnsrggwakrrlzbpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaXJsbnNyZ2d3YWtycmx6YnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDYzMDYsImV4cCI6MjA3MDg4MjMwNn0.3tygBnElpITu9c4QW9mAytdFHMOJl7jF1_y2yVth0YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
